version: '3'

services:
  web:
    image: nginx:1.14-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./auth:/auth
      - ./certs:/certs
      - ./config/nginx:/etc/nginx
      - ./data/www:/data/www
    links:
      - gogs:gogs

  gogs:
    image: gogs/gogs:0.11.43
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - ./temp/gogs:/data
