version: '3'

services:
  web:
    image: nginx:1.14-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./auth:/auth
      - ./certs:/certs
      - ./config/nginx:/etc/nginx
      - ./data/www:/data/www
    links:
      - gogs:gogs
      - registry:registry
      - drone-server:drone-server

  gogs:
    image: gogs/gogs:0.11.43
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
      - ./temp/gogs:/data

  registry:
    image: registry:2
    ports:
      - 5000:5000
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_HTTP_TLS_KEY=/certs/registry.key
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.crt
    volumes:
      - ./auth:/auth
      - ./certs:/certs
      - ./temp/registry:/var/lib/registry

  drone-server:
    image: drone/drone:0.8
    ports:
      - 20080:8000
      - 20090:9000
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=https://ci.demo.com
      - DRONE_SECRET=drone-secret
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=http://git.demo.com:3000
    volumes:
      - ./temp/drone:/var/lib/drone
    links:
      - gogs:git.demo.com

  drone-agent:
    image: drone/agent:0.8
    environment:
      - DRONE_SERVER=ci.demo.com:20090
      - DRONE_SECRET=drone-secret
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
