version: '3'

services:
  web:
    image: nginx:1.14-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./auth:/auth
      - ./certs:/certs
      - ./config/nginx:/etc/nginx
      - ./data/www:/data/www
